version: '3.7'

services:  
  equinox_data_server:
    image: muratartim/equinox_data_server
    ports:
      - '1235:1235'
    environment:
      - ds.hostname=equinox_mysql_server
      - ds.port=3306
      - ds.databaseName=AFTwin
      - ds.username=root
      - ds.password=Martim_17891917
      - sftp.hostname=equinox_sftp_server
      - sftp.password=17891917
      - sftp.port=22
      - sftp.rootPath=filerRoot/
      - sftp.username=aurora
      - uploadConnectionSettings=false
  
  ouroboros:
    image: muratartim/ouroboros
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 60 --cleanup
    depends_on:
      - "equinox_data_server"